[package]
name = "mltt-span"
version = "0.1.0"
authors = ["Brendan Zabarauskas <bjzaba@yahoo.com.au>"]
description = "Data structures for tracking source positions in the MLTT language"
license = "MIT"
edition = "2018"
publish = false

[dependencies]
unicode-segmentation = "1.3.0"
pretty_assertions = "0.6"
language-reporting = "0.4.0"
