[package]
name = "mltt-parse"
version = "0.1.0"
authors = ["Brendan Zabarauskas <bjzaba@yahoo.com.au>"]
description = "The parser for the MLTT language"
license = "MIT"
edition = "2018"
publish = false

[dependencies]
language-reporting = "0.4.0"
log = "0.4"
mltt-concrete = { path = "../mltt-concrete" }
mltt-span = { path = "../mltt-span" }
pretty_assertions = "0.6"

[dev-dependencies]
pretty_env_logger = "0.3"
